forms_api:
  # Empty key bypasses authentication process all together (mostly used by tests so we dont need to authenticate
  # every request spec
  authentication_key:

features:
  accept_legacy_answer_types: false
